name: Create Release

on:
  push:
    tags:
      - 'OVIS-4*'
      - 'v[0-9]+.[0-9]+.[0-9]+**'

jobs:
  build:
    name: Create Release
    # Make sure that test-make-dist.yaml has the same "runs-on" and
    # "container" as used here.
    runs-on: ubuntu-latest
    container:
        image: ovishpc/ovis-ubuntu-build
    permissions:
        contents: write

    steps:
    - uses: actions/checkout@v3
    # actions/checkout breaks annotated tags by converting them into
    # lightweight tags, so we need to force fetch the tag again
    # See: https://github.com/actions/checkout/issues/290
    - name: Repair tag
      run: git fetch -f origin ${{ github.ref }}:${{ github.ref }}
    - name: Verify tag is annotated
      run: if test x$(git for-each-ref ${{ github.ref }} | awk '{print $2}') = xtag; then /bin/true; else echo "\"${{ github.ref }}\" does not look like an annotated tag!"; /bin/false; fi
    - name: autogen.sh
      run: sh autogen.sh
    - name: configure
      run: ./configure
    - name: make dist
      run: |
        make dist
        echo TARBALL_NAME=$(ls *.tar.gz | head -1) >> $GITHUB_ENV
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./${{ env.TARBALL_NAME }}
  dispatch-container-bake:
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: dispatch ldms-containers bake
        run: |
          set -e
          sed -i "s|LDMS_TAG|${{github.ref_name}}|" .github/data/dispatch.yaml
          sed -i "s|LDMS_REPO_URL|${{github.server_url}}/${{github.repository}}|" .github/data/dispatch.yaml
          python3 -c 'import sys,yaml,json; print(json.dumps(yaml.load(sys.stdin, yaml.SafeLoader)))' < .github/data/dispatch.yaml > dispatch.json
          curl -L -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{secrets.NARATEGITHUB_LDMS_CONTAINERS_TOKEN}}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -d "@dispatch.json" \
            "https://api.github.com/repos/narategithub/ldms-containers/actions/workflows/on_ldms_release.yaml/dispatches"
